pipeline {
    
	agent { label 'slave2' } 
	
	libraries {
		lib('printuser@main')
	}

	stages {
			
			stage('Build') {
					steps {
						catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {	
							sh ''' 
									getUser 'Harsha' 'Trainee'
							   '''
						}	   
					}
			}
					
			stage('Test and Deploy') { 
				
				parallel {
					stage('Test') { 
						steps {
							sh '''
								   echo "$NODE_NAME -> $JOB_NAME -> $BUILD_NUMBER "
								   sleep 5
							   ''' 
						}
					}
					
					stage('Deploy') { 
						steps {
							sh ''' 
									echo "STAGE 3: This is a Deploy stage"
									sleep 5
							   '''
						}
					}
		
				}	
			}
    }
}
