pipeline {
    
	agent none 
    
	stages {
        
		stage('Build') { 
			
			agent { label 'master' }
			
            steps {
                sh ''' 
						echo "STAGE 1: This is a build stage"
						sleep 5
				   '''
            }
        }
        
		stage('Test') { 
			
			agent { label 'slave2' }
			
            steps {
                sh '''
					   echo "STAGE 2: This is a Test stage"
					   sleep 5
				   ''' 
            }
        }
		
        stage('Deploy') { 
		
			agent { label 'master' }
        
			steps {
                sh ''' 
						echo "STAGE 3: This is a Deploy stage"
						sleep 5
				   '''
            }
        }
    }
}
