pipeline {
    
	agent { label 'slave2' } 
    
	environment {
		TEST = "pipeline_level"
	}
	
	stages {
			
			stage('Build') {
				environment {
					TEST = "stage_level"
				}
				steps {
					sh ''' 
							echo "STAGE 1: This is a build stage $TEST"
							sleep 5
					   '''
				}
			}
					
			stage('Test and Deploy') { 
				
				input {
					message 'Press yes to continue'
				}
				
				parallel {
					stage('Test') { 
						steps {
							sh '''
								   echo "STAGE 2: This is a Test stage $TEST"
								   sleep 5
							   ''' 
						}
					}
					
					stage('Deploy') { 
						steps {
							sh ''' 
									echo "STAGE 3: This is a Deploy stage $TEST"
									sleep 5
							   '''
						}
					}
		
				}	
			}
    }
}
